/* Embed a numeric record as a JS module of base64 Float64 blocks. */
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2], out = process.argv[3];
const text = readFileSync(src, 'utf8');
const t = [], re = [], im = [];
for (const line of text.split('\n')) {
  const s = line.trim();
  if (!s || s[0] === '#') continue;
  const p = s.split(/\s+/).map(Number);
  if (p.length >= 3 && p.every(Number.isFinite)) { t.push(p[0]); re.push(p[1]); im.push(p[2]); }
  else if (p.length === 2 && p.every(Number.isFinite)) { t.push(t.length); re.push(p[0]); im.push(p[1]); }
  else if (p.length === 1 && Number.isFinite(p[0])) { t.push(t.length); re.push(p[0]); im.push(0); }
}
const b64 = a => Buffer.from(Float64Array.from(a).buffer).toString('base64');
const name = src.split('/').pop();
writeFileSync(out, `/* GENERATED by tools/embed.mjs from ${name} — do not edit by hand.
   The record as raw Float64 blocks; decode with CORE.decodeF64(). n=${t.length} */
const GSFC={name:${JSON.stringify(name)},n:${t.length},t:"${b64(t)}",re:"${b64(re)}",im:"${b64(im)}"};
`);
console.log(`embedded ${t.length} samples from ${name} -> ${out}`);
